import re
import streamlit as st
import json
import pandas as pd
import altair as alt

st.set_page_config(page_title="AGTA Persona Explorer", layout="wide")

TRANSPORT_KEYWORDS = [
    "walk to", "walked to", "walking to",
    "cycle", "cycling", "cycled",
    "bike", "biking", "biked", "bicycle",
    "drove", "driving",
    "commut",
    "bus stop", "train station", "tram", "subway", "metro station",
    "taxi", "uber", "e-scooter",
    "motorcycle", "traffic", "highway", "freeway",
    "parking lot", "vehicle", "automobile",
]

uploaded = st.sidebar.file_uploader("Load persona JSON", type="json")
if not uploaded:
    st.title("AGTA Persona Explorer")
    st.info("Upload a persona JSON file generated by `agta.personas.generate` to begin.")
    st.stop()

raw = json.load(uploaded)

rows = []
for pid, entry in raw.items():
    row = {"pid": pid, "persona": entry["persona"], "city": entry.get("city", ""), "model": entry.get("model", "")}
    for k, v in entry.get("demographics", {}).items():
        row[k] = v
    for k, v in (entry.get("attitudes") or {}).items():
        row[f"att_{k}"] = v
    rows.append(row)
df = pd.DataFrame(rows)

name_pattern = re.compile(r"^(?:I am|I['\u2019]m|My name is|Ich bin|Ich heiße|Mein Name ist)\s+(\w+)", re.IGNORECASE)
df["name"] = df["persona"].apply(lambda t: m.group(1) if (m := name_pattern.search(t)) else None)

att_cols = [c for c in df.columns if c.startswith("att_")]

view = st.sidebar.radio("View", ["Overview", "Browse", "Names", "Transport Leaks", "Demographics", "Attitudes", "Search"])

# ── Overview ──
if view == "Overview":
    st.title("Persona Overview")
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Personas", len(df))
    col2.metric("Unique Names", df["name"].nunique())
    models = df["model"].unique()
    col3.metric("Models", ", ".join(models) if len(models) <= 3 else f"{len(models)} models")

    st.subheader("Region Distribution")
    region_counts = df["city"].value_counts()
    st.bar_chart(region_counts)

    st.subheader("Sample Persona")
    sample = df.sample(1).iloc[0]
    st.markdown(f"**{sample['name']}** ({sample.get('age', '?')}, {sample.get('gender', '?')}, {sample['city']})")
    st.write(sample["persona"])

# ── Browse ──
elif view == "Browse":
    st.title("Browse Personas")

    filters = {}
    if "gender" in df.columns:
        opts = ["All"] + sorted(df["gender"].dropna().unique().tolist())
        sel = st.sidebar.selectbox("Gender", opts)
        if sel != "All":
            filters["gender"] = sel
    if "age" in df.columns:
        age_min, age_max = int(df["age"].min()), int(df["age"].max())
        age_range = st.sidebar.slider("Age", age_min, age_max, (age_min, age_max))
        filters["age_range"] = age_range
    if "education" in df.columns:
        opts = ["All"] + sorted(df["education"].dropna().unique().tolist())
        sel = st.sidebar.selectbox("Education", opts)
        if sel != "All":
            filters["education"] = sel
    if "employed" in df.columns:
        opts = ["All"] + sorted(df["employed"].dropna().astype(str).unique().tolist())
        sel = st.sidebar.selectbox("Employed", opts)
        if sel != "All":
            filters["employed"] = sel

    filtered = df.copy()
    if "gender" in filters:
        filtered = filtered[filtered["gender"] == filters["gender"]]
    if "age_range" in filters:
        filtered = filtered[(filtered["age"] >= filters["age_range"][0]) & (filtered["age"] <= filters["age_range"][1])]
    if "education" in filters:
        filtered = filtered[filtered["education"] == filters["education"]]
    if "employed" in filters:
        filtered = filtered[filtered["employed"].astype(str) == filters["employed"]]

    st.write(f"Showing {len(filtered)} of {len(df)} personas")

    cols_per_row = 3
    rows_to_show = filtered.head(21)
    for i in range(0, len(rows_to_show), cols_per_row):
            cols = st.columns(cols_per_row)
            for j, col in enumerate(cols):
                idx = i + j
                if idx >= len(rows_to_show):
                    break
                row = rows_to_show.iloc[idx]
                with col:
                    with st.container(border=True):
                        st.markdown(f"**{row['name'] or 'Unknown'}**, {row.get('age', '?')}, {row.get('gender', '?')}")
                        st.caption(row["city"])
                        with st.expander("Read more"):
                            st.write(row["persona"])

# ── Names ──
elif view == "Names":
    st.title("Name Analysis")
    name_counts = df["name"].value_counts()

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Personas", len(df))
    col2.metric("Unique Names", df["name"].nunique())
    col3.metric("Unnamed", df["name"].isna().sum())

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Most Common")
        st.dataframe(name_counts.head(15).reset_index().rename(columns={"name": "Name", "count": "Count"}), hide_index=True, height=300)
    with col2:
        st.subheader("Top 20")
        st.bar_chart(name_counts.head(20), height=300)

    if "gender" in df.columns:
        st.subheader("Top Names by Gender")
        genders = sorted(df["gender"].dropna().unique().tolist())
        cols = st.columns(len(genders))
        for col, gender in zip(cols, genders):
            with col:
                st.write(f"**{gender}**")
                gcounts = df[df["gender"] == gender]["name"].value_counts().head(10)
                st.dataframe(gcounts.reset_index().rename(columns={"name": "Name", "count": "Count"}), hide_index=True, height=250)

# ── Transport Leaks ──
elif view == "Transport Leaks":
    st.title("Transport Leak Detection")

    def find_leaks(text):
        found = []
        lower = text.lower()
        for kw in TRANSPORT_KEYWORDS:
            if kw in lower:
                found.append(kw.strip())
        return found

    df["leaks"] = df["persona"].apply(find_leaks)
    df["leak_count"] = df["leaks"].apply(len)
    leaked = df[df["leak_count"] > 0].copy()

    col1, col2 = st.columns(2)
    col1.metric("Clean Personas", len(df) - len(leaked))
    col2.metric("With Leaks", len(leaked))

    if len(leaked) > 0:
        st.subheader("Keyword Frequency")
        all_kws = [kw for kws in leaked["leaks"] for kw in kws]
        kw_counts = pd.Series(all_kws).value_counts()
        st.bar_chart(kw_counts)

        st.subheader("Leaked Personas")
        for _, row in leaked.iterrows():
            with st.expander(f"{row['name'] or row['pid']} — leaked: {', '.join(row['leaks'])}"):
                text = row["persona"]
                for kw in row["leaks"]:
                    text = re.sub(rf"({re.escape(kw)})", r"**\1**", text, flags=re.IGNORECASE)
                st.markdown(text)

# ── Demographics ──
elif view == "Demographics":
    st.title("Demographic Distributions")

    col1, col2 = st.columns(2)
    with col1:
        if "age" in df.columns:
            c = alt.Chart(df).mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3).encode(
                x=alt.X("age:Q", bin=alt.Bin(maxbins=20), title="Age"),
                y=alt.Y("count()", title=""),
                tooltip=["age", "count()"],
            ).properties(height=180, title="Age")
            st.altair_chart(c, use_container_width=True)
    with col2:
        if "gender" in df.columns:
                    c = alt.Chart(df).mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3).encode(
                        x=alt.X("gender:N", title=""),
                        y=alt.Y("count()", title=""),
                        color=alt.Color("gender:N", legend=None),
                        tooltip=["gender", "count()"],
                    ).properties(height=180, title="Gender")
                    st.altair_chart(c, use_container_width=True)

    col3, col4 = st.columns(2)
    with col3:
        if "education" in df.columns:
            c = alt.Chart(df).mark_bar(cornerRadiusEnd=3).encode(
                x=alt.X("count()", title=""),
                y=alt.Y("education:N", sort="-x", title=""),
                tooltip=["education", "count()"],
            ).properties(height=180, title="Education")
            st.altair_chart(c, use_container_width=True)
    with col4:
        if "employed" in df.columns:
                    c = alt.Chart(df).mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3).encode(
                        x=alt.X("employed:N", title=""),
                        y=alt.Y("count()", title=""),
                        color=alt.Color("employed:N", legend=None),
                        tooltip=["employed", "count()"],
                    ).properties(height=180, title="Employment")
                    st.altair_chart(c, use_container_width=True)

    col5, col6 = st.columns(2)
    with col5:
        if "household type" in df.columns:
            c = alt.Chart(df).mark_bar(cornerRadiusEnd=3).encode(
                x=alt.X("count()", title=""),
                y=alt.Y("household type:N", sort="-x", title=""),
                tooltip=["household type", "count()"],
            ).properties(height=200, title="Household Type")
            st.altair_chart(c, use_container_width=True)
    with col6:
        if "household income" in df.columns:
            income_df = df[["household income"]].dropna().copy()
            income_df["income"] = income_df["household income"].apply(lambda x: int(re.sub(r"[^\d]", "", x.split("+")[0].split("/")[0])) if isinstance(x, str) else x)
            c = alt.Chart(income_df).mark_bar(cornerRadiusTopLeft=3, cornerRadiusTopRight=3).encode(
                x=alt.X("income:Q", bin=alt.Bin(maxbins=20), title="EUR/month"),
                y=alt.Y("count()", title=""),
                tooltip=["income", "count()"],
            ).properties(height=200, title="Household Income")
            st.altair_chart(c, use_container_width=True)

# ── Attitudes ──
elif view == "Attitudes":
    st.title("Attitude Distributions")
    if not att_cols:
        st.info("No attitude data found in this persona set.")
    else:
        for col in att_cols:
            label = col.replace("att_", "")
            st.subheader(label)
            st.bar_chart(df[col].dropna().astype(int).value_counts().sort_index())

# ── Search ──
elif view == "Search":
    st.title("Search Personas")
    query = st.text_input("Search text")
    if query:
        matches = df[df["persona"].str.contains(query, case=False, na=False)]
        st.write(f"{len(matches)} matches")
        for _, row in matches.head(20).iterrows():
            with st.expander(f"{row['name'] or row['pid']} — {row.get('age', '?')}, {row.get('gender', '?')}"):
                text = re.sub(rf"({re.escape(query)})", r"**\1**", row["persona"], flags=re.IGNORECASE)
                st.markdown(text)